definitions:
  handlers.rateItem:
    properties:
      date:
        type: string
      description:
        type: number
      name:
        type: string
      title:
        type: string
    type: object
  handlers.rateResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/handlers.rateItem'
        type: array
      success:
        type: boolean
    type: object
  handlers.saveResponse:
    properties:
      success:
        type: boolean
    type: object
host: localhost
info:
  contact: {}
  description: Description of the service
  title: Nat Service
  version: "1.0"
paths:
  /currency/save/{date}:
    get:
      parameters:
      - description: date
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response
          schema:
            $ref: '#/definitions/handlers.saveResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: По указанной дате сохранять курсы валют в БД
      tags:
      - kmf
  /currency/save/{date}/{code}:
    get:
      parameters:
      - description: date
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: response
          schema:
            $ref: '#/definitions/handlers.rateResponse'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: По указанной дате показать курсы валют из БД
      tags:
      - kmf
schemes:
- http
swagger: "2.0"
